version: 2
updates:
  - package-ecosystem: cargo
    directories: ["/"]
    schedule:
      interval: disabled
  - package-ecosystem: github-actions
    directories: ["/"]
    schedule:
      interval: disabled
