name: Publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check version
        uses: tcurdt/action-verify-version-cargo@master

  publish_crates_io:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: [check-version]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish
        run: |
          cargo publish \
            --verbose \
            --no-verify \
            --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

  create_release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    needs: [publish_crates_io]
    permissions:
      contents: write
    steps:
      # Do a full checkout, to make sure, the changelog is complete
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate changelog for release
        uses: orhun/git-cliff-action@v3
        id: changelog
        with:
          config: cliff.toml
          args: --latest --no-exec --github-repo ${{ github.repository }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref, '-') }}
          generate_release_notes: false
          body: ${{ steps.changelog.outputs.content }}
